### ISSUE TITLE
rstudio builds fail

### ISSUE THREAD

**Issue by pitkant** [CSCfi/rstudio-openshift#9]
When attempting to replicate the example described in README.md, I get the following failure messages:

BuildConfig: rstudio
Pull builder image failed
```
Cloning "https://github.com/CSCfi/rstudio-openshift.git " ...
--
Commit:	20598dd1a2ac0b5fe509646c6dfea62df5b5d062 (Merge pull request #8 from CSCfi/shiny-deploy)
Author:	Alvaro Gonzalez <tychoma4@gmail.com>
Date:	Tue Jan 3 09:04:29 2023 +0200
 
Pulling image rocker/tidyverse:4.1.3 ...
error: build error: failed to pull image: manifest for docker.io/rocker/tidyverse:4.1.3 not found
```

Is there any additional information, aside from the one given in the README.md, that I should know to get the example working?

**Comment by lvarin** [comment]
This is an old issue caused by the old version that Rahti uses, which does not recognize the new OCI format for images

**Comment by lvarin** [comment]
It has been solved by caching a copy in Rahti's registry
